# Generated by Django 2.1.2 on 2018-10-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181030_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hunter',
            new_name='user',
        ),
    ]
